version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: cloudide-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cloudide
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: cloudide-redis
    ports:
      - "6379:6379"

  gateway:
    build: ./services/gateway
    ports:
      - "5000:5000"
    volumes:
      - ./services/gateway:/app

  auth-service:
    build: ./services/auth-service
    ports:
      - "5001:5001"
    volumes:
      - ./services/auth-service:/app

  execution-engine:
    build: ./services/execution-engine
    ports:
      - "5002:5002"
    volumes:
      - ./services/execution-engine:/app
